name = "DynamicPlots"
uuid = "a7562ee3-23e5-4f09-9cc3-be128489fa0b"
authors = ["Nikolas Siccha and contributors"]
version = "0.1.0"

[deps]
DynamicObjects = "23d02862-63fe-4c6e-8fdb-1d52cbbd39d5"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
DynamicObjects = "0.1"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
